INSERT INTO article (title, content) VALUES ('[입사] 2023-2학기 기숙사 지원 안내', '기숙사 지원 마감일은 2023.xx.xx 입니다.')
INSERT INTO article (title, content) VALUES ('[식당] 여름방학 식당 운영 시간 안내', '여름방학 동안 식당 운영 시간은 xx~xx 입니다.')
INSERT INTO article (title, content) VALUES ('[관리] 동별 누수 점검 날짜 안내', '동별 누수 점검 날짜를 아래와 같이 안내드립니다.')
INSERT INTO article (title, content) VALUES ('[퇴사] 2023 여름학기 퇴사 날짜 안내', '여름학기 기숙사 퇴사 날짜는 2023.xx.xx 입니다.')
INSERT INTO article (title, content) VALUES ('[퇴사] 2023 여름학기 퇴사 날짜 안내', '여름학기 기숙사 퇴사 날짜는 2023.xx.xx 입니다.')
INSERT INTO article (title, content) VALUES ('[퇴사] 2023 여름학기 퇴사 날짜 안내', '여름학기 기숙사 퇴사 날짜는 2023.xx.xx 입니다.')
INSERT INTO article (title, content) VALUES ('[퇴사] 2023 여름학기 퇴사 날짜 안내', '여름학기 기숙사 퇴사 날짜는 2023.xx.xx 입니다.')
INSERT INTO article (title, content) VALUES ('[퇴사] 2023 여름학기 퇴사 날짜 안내', '여름학기 기숙사 퇴사 날짜는 2023.xx.xx 입니다.')
INSERT INTO article (title, content) VALUES ('[퇴사] 2023 여름학기 퇴사 날짜 안내', '여름학기 기숙사 퇴사 날짜는 2023.xx.xx 입니다.')